// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/grpc/calendar.proto

package calendar

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Event struct {
	Start                *timestamp.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End                  *timestamp.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	Payload              string               `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa81cb4b2bc0d829, []int{0}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetStart() *timestamp.Timestamp {
	if m != nil {
		return m.Start
	}
	return nil
}

func (m *Event) GetEnd() *timestamp.Timestamp {
	if m != nil {
		return m.End
	}
	return nil
}

func (m *Event) GetPayload() string {
	if m != nil {
		return m.Payload
	}
	return ""
}

type GetEventsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetEventsRequest) Reset()         { *m = GetEventsRequest{} }
func (m *GetEventsRequest) String() string { return proto.CompactTextString(m) }
func (*GetEventsRequest) ProtoMessage()    {}
func (*GetEventsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa81cb4b2bc0d829, []int{1}
}

func (m *GetEventsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetEventsRequest.Unmarshal(m, b)
}
func (m *GetEventsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetEventsRequest.Marshal(b, m, deterministic)
}
func (m *GetEventsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetEventsRequest.Merge(m, src)
}
func (m *GetEventsRequest) XXX_Size() int {
	return xxx_messageInfo_GetEventsRequest.Size(m)
}
func (m *GetEventsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetEventsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetEventsRequest proto.InternalMessageInfo

type EventList struct {
	Events               []*Event `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventList) Reset()         { *m = EventList{} }
func (m *EventList) String() string { return proto.CompactTextString(m) }
func (*EventList) ProtoMessage()    {}
func (*EventList) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa81cb4b2bc0d829, []int{2}
}

func (m *EventList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventList.Unmarshal(m, b)
}
func (m *EventList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventList.Marshal(b, m, deterministic)
}
func (m *EventList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventList.Merge(m, src)
}
func (m *EventList) XXX_Size() int {
	return xxx_messageInfo_EventList.Size(m)
}
func (m *EventList) XXX_DiscardUnknown() {
	xxx_messageInfo_EventList.DiscardUnknown(m)
}

var xxx_messageInfo_EventList proto.InternalMessageInfo

func (m *EventList) GetEvents() []*Event {
	if m != nil {
		return m.Events
	}
	return nil
}

type EventUpdateInfo struct {
	EventId              uint32   `protobuf:"varint,1,opt,name=eventId,proto3" json:"eventId,omitempty"`
	Event                *Event   `protobuf:"bytes,2,opt,name=event,proto3" json:"event,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventUpdateInfo) Reset()         { *m = EventUpdateInfo{} }
func (m *EventUpdateInfo) String() string { return proto.CompactTextString(m) }
func (*EventUpdateInfo) ProtoMessage()    {}
func (*EventUpdateInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa81cb4b2bc0d829, []int{3}
}

func (m *EventUpdateInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventUpdateInfo.Unmarshal(m, b)
}
func (m *EventUpdateInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventUpdateInfo.Marshal(b, m, deterministic)
}
func (m *EventUpdateInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventUpdateInfo.Merge(m, src)
}
func (m *EventUpdateInfo) XXX_Size() int {
	return xxx_messageInfo_EventUpdateInfo.Size(m)
}
func (m *EventUpdateInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_EventUpdateInfo.DiscardUnknown(m)
}

var xxx_messageInfo_EventUpdateInfo proto.InternalMessageInfo

func (m *EventUpdateInfo) GetEventId() uint32 {
	if m != nil {
		return m.EventId
	}
	return 0
}

func (m *EventUpdateInfo) GetEvent() *Event {
	if m != nil {
		return m.Event
	}
	return nil
}

type EventId struct {
	Id                   uint32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EventId) Reset()         { *m = EventId{} }
func (m *EventId) String() string { return proto.CompactTextString(m) }
func (*EventId) ProtoMessage()    {}
func (*EventId) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa81cb4b2bc0d829, []int{4}
}

func (m *EventId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventId.Unmarshal(m, b)
}
func (m *EventId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventId.Marshal(b, m, deterministic)
}
func (m *EventId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventId.Merge(m, src)
}
func (m *EventId) XXX_Size() int {
	return xxx_messageInfo_EventId.Size(m)
}
func (m *EventId) XXX_DiscardUnknown() {
	xxx_messageInfo_EventId.DiscardUnknown(m)
}

var xxx_messageInfo_EventId proto.InternalMessageInfo

func (m *EventId) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Event)(nil), "Event")
	proto.RegisterType((*GetEventsRequest)(nil), "GetEventsRequest")
	proto.RegisterType((*EventList)(nil), "EventList")
	proto.RegisterType((*EventUpdateInfo)(nil), "EventUpdateInfo")
	proto.RegisterType((*EventId)(nil), "EventId")
}

func init() { proto.RegisterFile("internal/grpc/calendar.proto", fileDescriptor_fa81cb4b2bc0d829) }

var fileDescriptor_fa81cb4b2bc0d829 = []byte{
	// 317 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0xcd, 0x6a, 0xfa, 0x40,
	0x14, 0xc5, 0x1d, 0xc5, 0xaf, 0x1b, 0xfe, 0xff, 0xda, 0x59, 0xa5, 0x41, 0xac, 0x4c, 0x37, 0x82,
	0x32, 0x29, 0xf6, 0x09, 0x4a, 0x2b, 0x45, 0xe8, 0x2a, 0xb4, 0x0f, 0x30, 0x3a, 0x57, 0x09, 0xc4,
	0x99, 0x34, 0x19, 0x0b, 0x5d, 0xf6, 0x75, 0xfa, 0x94, 0xc5, 0xf9, 0x08, 0xe8, 0xa6, 0xbb, 0xdc,
	0x7b, 0x7e, 0xe7, 0xe6, 0xe4, 0x04, 0xc6, 0xb9, 0x32, 0x58, 0x29, 0x51, 0xa4, 0xfb, 0xaa, 0xdc,
	0xa6, 0x5b, 0x51, 0xa0, 0x92, 0xa2, 0xe2, 0x65, 0xa5, 0x8d, 0x4e, 0x6e, 0xf7, 0x5a, 0xef, 0x0b,
	0x4c, 0xed, 0xb4, 0x39, 0xee, 0x52, 0x93, 0x1f, 0xb0, 0x36, 0xe2, 0x50, 0x3a, 0x80, 0x7d, 0x13,
	0xe8, 0xae, 0x3e, 0x51, 0x19, 0x7a, 0x0f, 0xdd, 0xda, 0x88, 0xca, 0xc4, 0x64, 0x4a, 0x66, 0xd1,
	0x32, 0xe1, 0xce, 0xca, 0x83, 0x95, 0xbf, 0x05, 0x6b, 0xe6, 0x40, 0xba, 0x80, 0x0e, 0x2a, 0x19,
	0xb7, 0xff, 0xe4, 0x4f, 0x18, 0x8d, 0xa1, 0x5f, 0x8a, 0xaf, 0x42, 0x0b, 0x19, 0x77, 0xa6, 0x64,
	0x36, 0xcc, 0xc2, 0xc8, 0x28, 0x8c, 0x5e, 0xd0, 0xd8, 0x14, 0x75, 0x86, 0x1f, 0x47, 0xac, 0x0d,
	0x9b, 0xc3, 0xd0, 0x2e, 0x5e, 0xf3, 0xda, 0xd0, 0x09, 0xf4, 0xd0, 0xaa, 0x31, 0x99, 0x76, 0x66,
	0xd1, 0xb2, 0xc7, 0xad, 0x96, 0xf9, 0x2d, 0x5b, 0xc3, 0x95, 0x5d, 0xbc, 0x97, 0x52, 0x18, 0x5c,
	0xab, 0x9d, 0x3e, 0xbd, 0xcd, 0x8a, 0x6b, 0x69, 0xbf, 0xe7, 0x5f, 0x16, 0x46, 0x3a, 0x86, 0xae,
	0x7d, 0xf4, 0xb9, 0xc3, 0x2d, 0xb7, 0x64, 0x37, 0xd0, 0x5f, 0x79, 0xf0, 0x3f, 0xb4, 0xf3, 0xe0,
	0x6e, 0xe7, 0x72, 0xf9, 0x43, 0x60, 0xf0, 0xe4, 0xeb, 0xa5, 0x13, 0x18, 0x3c, 0x4a, 0xe9, 0x9a,
	0xf3, 0x27, 0x92, 0x01, 0xf7, 0x56, 0xd6, 0xa2, 0x73, 0x88, 0x5c, 0x1a, 0x87, 0x8c, 0xf8, 0x45,
	0xc0, 0x33, 0xf8, 0x0e, 0xa2, 0x67, 0x2c, 0x30, 0xc0, 0x8d, 0x74, 0x06, 0x2d, 0x60, 0xd8, 0xb4,
	0x44, 0xaf, 0xf9, 0x65, 0x63, 0x09, 0xf0, 0xa6, 0x30, 0xd6, 0xda, 0xf4, 0xec, 0x6f, 0x78, 0xf8,
	0x0d, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x6e, 0xb6, 0xfb, 0x1f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalendarClient is the client API for Calendar service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalendarClient interface {
	AddEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*EventId, error)
	UpdateEvent(ctx context.Context, in *EventUpdateInfo, opts ...grpc.CallOption) (*EventId, error)
	DeleteEvent(ctx context.Context, in *EventId, opts ...grpc.CallOption) (*EventId, error)
	GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*EventList, error)
}

type calendarClient struct {
	cc *grpc.ClientConn
}

func NewCalendarClient(cc *grpc.ClientConn) CalendarClient {
	return &calendarClient{cc}
}

func (c *calendarClient) AddEvent(ctx context.Context, in *Event, opts ...grpc.CallOption) (*EventId, error) {
	out := new(EventId)
	err := c.cc.Invoke(ctx, "/Calendar/AddEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarClient) UpdateEvent(ctx context.Context, in *EventUpdateInfo, opts ...grpc.CallOption) (*EventId, error) {
	out := new(EventId)
	err := c.cc.Invoke(ctx, "/Calendar/UpdateEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarClient) DeleteEvent(ctx context.Context, in *EventId, opts ...grpc.CallOption) (*EventId, error) {
	out := new(EventId)
	err := c.cc.Invoke(ctx, "/Calendar/DeleteEvent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarClient) GetEvents(ctx context.Context, in *GetEventsRequest, opts ...grpc.CallOption) (*EventList, error) {
	out := new(EventList)
	err := c.cc.Invoke(ctx, "/Calendar/GetEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalendarServer is the server API for Calendar service.
type CalendarServer interface {
	AddEvent(context.Context, *Event) (*EventId, error)
	UpdateEvent(context.Context, *EventUpdateInfo) (*EventId, error)
	DeleteEvent(context.Context, *EventId) (*EventId, error)
	GetEvents(context.Context, *GetEventsRequest) (*EventList, error)
}

// UnimplementedCalendarServer can be embedded to have forward compatible implementations.
type UnimplementedCalendarServer struct {
}

func (*UnimplementedCalendarServer) AddEvent(ctx context.Context, req *Event) (*EventId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddEvent not implemented")
}
func (*UnimplementedCalendarServer) UpdateEvent(ctx context.Context, req *EventUpdateInfo) (*EventId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateEvent not implemented")
}
func (*UnimplementedCalendarServer) DeleteEvent(ctx context.Context, req *EventId) (*EventId, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEvent not implemented")
}
func (*UnimplementedCalendarServer) GetEvents(ctx context.Context, req *GetEventsRequest) (*EventList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEvents not implemented")
}

func RegisterCalendarServer(s *grpc.Server, srv CalendarServer) {
	s.RegisterService(&_Calendar_serviceDesc, srv)
}

func _Calendar_AddEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Event)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).AddEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/AddEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).AddEvent(ctx, req.(*Event))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calendar_UpdateEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventUpdateInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).UpdateEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/UpdateEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).UpdateEvent(ctx, req.(*EventUpdateInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calendar_DeleteEvent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).DeleteEvent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/DeleteEvent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).DeleteEvent(ctx, req.(*EventId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Calendar_GetEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEventsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServer).GetEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Calendar/GetEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServer).GetEvents(ctx, req.(*GetEventsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Calendar_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Calendar",
	HandlerType: (*CalendarServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddEvent",
			Handler:    _Calendar_AddEvent_Handler,
		},
		{
			MethodName: "UpdateEvent",
			Handler:    _Calendar_UpdateEvent_Handler,
		},
		{
			MethodName: "DeleteEvent",
			Handler:    _Calendar_DeleteEvent_Handler,
		},
		{
			MethodName: "GetEvents",
			Handler:    _Calendar_GetEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/grpc/calendar.proto",
}
